# Generated by Django 5.2.1 on 2025-06-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=100)),
                ('pais', models.CharField(choices=[('BOL', 'BOLIVIA')], max_length=3)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('dominio', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
    ]
