# Generated by Django 5.2.1 on 2025-05-23 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargo', '0001_initial'),
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoDepartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargo_departamentos', to='cargo.cargo')),
                ('id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departamento_cargos', to='departamento.departamento')),
            ],
            options={
                'unique_together': {('id_cargo', 'id_departamento')},
            },
        ),
    ]
