# Generated by Django 5.2.1 on 2025-05-21 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargo_departamento', '0001_initial'),
        ('empleado', '0002_remove_empleado_departamento_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contrato', models.CharField(choices=[('INDEFINIDO', 'Indefinido'), ('PLAZO FIJO', 'Plazo fijo'), ('MEDIO TIEMPO', 'Medio tiempo'), ('PASANTIA', 'Pasantía')], max_length=15)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('salario_personalizado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('FINALIZADO', 'Finalizado'), ('PENDIENTE', 'Pendiente'), ('RENOVADO', 'Renovado')], max_length=12)),
                ('observaciones', models.CharField(max_length=100)),
                ('cargo_departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='cargo_departamento.cargodepartamento')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='empleado.empleado')),
            ],
        ),
    ]
