# Generated by Django 5.2.1 on 2025-05-21 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '0002_remove_empleado_departamento_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('observaciones', models.CharField(max_length=100)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='empleado.empleado')),
            ],
        ),
    ]
