# Generated by Django 5.2.1 on 2025-06-20 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asistencia', '0001_initial'),
        ('empleado', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='empleado.empleado'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('fecha', 'empleado')},
        ),
    ]
