# Generated by Django 5.2.1 on 2025-06-20 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorasExtras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_horas', models.DurationField()),
                ('estado', models.CharField(choices=[('PAGADO', 'Pagago'), ('IMPAGO', 'Impago')], max_length=7)),
                ('motivo', models.CharField(max_length=100)),
                ('fecha_autorizacion', models.DateField()),
                ('empleado_autorizador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horas_extras', to='empleado.empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
            ],
        ),
    ]
