# Generated by Django 5.2.1 on 2025-06-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas_extras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horasextras',
            name='aprobado',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
