FROM python:3.11

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY backend/requirements.txt ./backend/requirements.txt
RUN pip install --upgrade pip
RUN pip install -r backend/requirements.txt

COPY . .

# Gunicorn (comentado para producción futura)
# CMD ["gunicorn", "rrhh.wsgi:application", "--bind", "0.0.0.0:8000"]
