# Usa la imagen oficial de Node.js (al ser un proyecto frontend)
FROM node:18

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app/frontend

# Copia los archivos necesarios para instalar dependencias
COPY ../frontend/package*.json ./

# Instala las dependencias de React
RUN npm install

# Copia todo el código fuente del frontend
COPY ../frontend .

# Expone el puerto que usa React por defecto
EXPOSE 3000

# Comando por defecto para iniciar el frontend
CMD ["npm", "start"]
