# Generated by Django 5.2.1 on 2025-05-21 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='departamento_id',
        ),
    ]
