# Generated by Django 5.2.1 on 2025-06-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertheme',
            name='color_text',
            field=models.CharField(default='#8A8585', max_length=7),
        ),
    ]
