# Generated by Django 5.2.1 on 2025-06-03 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_text', models.CharField(default='#ffffff', max_length=7)),
                ('color1', models.CharField(default='#150546', max_length=7)),
                ('color2', models.CharField(default='#ffffff', max_length=7)),
                ('font_size', models.CharField(default='16px', max_length=10)),
                ('font_family', models.CharField(default='Arial, sans-serif', max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
