# Generated by Django 5.2.1 on 2025-06-06 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_alter_usertheme_color_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertheme',
            name='color1',
            field=models.CharField(default='#071DDC', max_length=7),
        ),
    ]
