# Generated by Django 5.2.1 on 2025-05-22 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documento', '0001_initial'),
        ('empleado', '0001_initial'),
        ('tipo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='empleado_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.empleado'),
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tipo.tipo'),
        ),
    ]
